name: beehive_app
description: A candidate application for Solution Challenge 2021.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  dependencies:
  table_calendar: ^2.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/Group 27.png
    - assets/images/bee.jpg
    - assets/images/person1.jpg
    - assets/images/person2.jpg
    - assets/images/person3.jpg
    - assets/images/person4.jpg
    - assets/images/person5.jpg
    - assets/images/person6.jpg
    - assets/images/person7.jpg
    - assets/images/person8.jpg

  fonts:
    - family: SF-Pro-Black
      fonts:
        - asset: fonts/SFPro/SF-Pro-Display-Black.otf

    - family: SF-Pro-BlackItalic
      fonts:
      - asset: fonts/SFPro/SF-Pro-Display-BlackItalic.otf
         
    - family: SF-Pro-Bold     
      fonts:
      - asset: fonts/SFPro/SF-Pro-Display-Bold.otf

    - family: SF-Pro-BoldItalic     
      fonts:          
      - asset: fonts/SFPro/SF-Pro-Display-BoldItalic.otf

    - family: SF-Pro-Heavy     
      fonts:       
      - asset: fonts/SFPro/SF-Pro-Display-Heavy.otf
    
    - family: SF-Pro-HeavyItalic     
      fonts:
      - asset: fonts/SFPro/SF-Pro-Display-HeavyItalic.otf

    - family: SF-Pro-Light     
      fonts:     
      - asset: fonts/SFPro/SF-Pro-Display-Light.otf

    - family: SF-Pro-LightItalic     
      fonts:         
      - asset: fonts/SFPro/SF-Pro-Display-LightItalic.otf

    - family: SF-Pro-Medium     
      fonts:     
      - asset: fonts/SFPro/SF-Pro-Display-Medium.otf

    - family: SF-Pro-MediumItalic     
      fonts:         
      - asset: fonts/SFPro/SF-Pro-Display-MediumItalic.otf

    - family: SF-Pro-Regular     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-Regular.otf

    - family: SF-Pro-RegularItalic     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-RegularItalic.otf

    - family: SF-Pro-Semibold     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-Semibold.otf

    - family: SF-Pro-SemiboldItalic    
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-SemiboldItalic.otf

    - family: SF-Pro-Thin     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-Thin.otf

    - family: SF-Pro-ThinItalic     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-ThinItalic.otf

    - family: SF-Pro-Ultralight     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-Ultralight.otf

    - family: SF-Pro-UltralightItalic     
      fonts:   
      - asset: fonts/SFPro/SF-Pro-Display-UltralightItalic.otf



